package com.example.issuereporting_service.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.ManyToOne;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.CascadeType;
import java.io.Serializable;
import java.util.List;

/* This model represents the Issue entity and it creates the issue table in the db.
 *  Columns are also created with the given names */
@Entity
@Table(name = "issue")
public class Issue implements Serializable {

    /* @Id annotation is used to create the primary key which is the id of the issue.
    Id is an autogenerated value */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "issue_id")
    private long id;

    // Below are the other columns in the issue table
    @Column(name = "issue_type")
    private String issueType;
    @Column(name = "issue_description")
    private String issueDescription;
    @Column(name = "issue_state")
    private String issueState;
    @Column(name = "created_time")
    private String createdTime;

    /* Below the relationship between the user table and issue table is created
     *  The user and issue tables are joined with a ManyToOne relationship
     *  The userId is created as a foreign key in the issue table */
    @ManyToOne(fetch = FetchType.EAGER, optional = false)
    @JoinColumn(name = "user_id")
    public User testUser;

    /*  Below the relationship between the user issue and issue_history table is created
     *  The issue and issue_history tables are joined with a OneToMany relationship */
    @OneToMany(mappedBy = "issue", fetch = FetchType.LAZY,
            cascade = CascadeType.ALL)
    private List<IssueHistory> issueHistories;

    // Default constructor of Issue
    public Issue() {
    }

    // This constructor is used for saving new issues
    public Issue(String issueType, String issueDescription, String issueState, String createdTime, User user) {
        this.issueType = issueType;
        this.issueDescription = issueDescription;
        this.issueState = issueState;
        this.createdTime = createdTime;
        this.testUser = user;
    }

    public Issue(int id, String issueType, String issueDescription, String issueState, String createdTime, User user) {
        this.id = id;
        this.issueType = issueType;
        this.issueDescription = issueDescription;
        this.issueState = issueState;
        this.createdTime = createdTime;
        this.testUser = user;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getIssueType() {
        return issueType;
    }

    public void setIssueType(String issueType) {
        this.issueType = issueType;
    }

    public String getIssueDescription() {
        return issueDescription;
    }

    public void setIssueDescription(String issueDescription) {
        this.issueDescription = issueDescription;
    }

    public String getIssueState() {
        return issueState;
    }

    public void setIssueState(String issueState) {
        this.issueState = issueState;
    }

    public String getCreatedTime() {
        return createdTime;
    }

    public void setCreatedTime(String createdTime) {
        this.createdTime = createdTime;
    }

    @Override
    public String toString() {
        return "Issue{" +
                "id=" + id +
                ", issueType='" + issueType + '\'' +
                ", issueDescription='" + issueDescription + '\'' +
                ", issueState='" + issueState + '\'' +
                ", createdTime='" + createdTime + '\'' +
                ", testUser=" + testUser +
                '}';
    }
}
